TB-1: add file type and fix tagging
Lumavate-Team/python-service-util pull request #52
Opened 2022-02-08 14:23 UTC by TheAndrewJackson

2022-02-08 14:24 UTC, TheAndrewJackson commented on aws/objects.py
> +    tags = f'OrgId={g.org_id}'
I made it `OrgId` to match what's in `file.py`

2022-02-08 15:01 UTC, ericseidel approved these changes

2022-02-09 18:08 UTC, abernathyc approved these changes

2022-02-09 21:09 UTC, ericseidel requested changes
Utilize the column type definitions when checking column types.

2022-02-09 21:09 UTC, ericseidel commented on base_asset/behavior/data_rest.py
> +      file_columns = [ column['columnName'] for column in column_defs if column['columnType']['value'] == 'file']
This should utilize the column type enum
```suggestion
      file_columns = [ column['columnName'] for column in column_defs if column['columnType']['value'] == enums.ColumnDataType.FILE.value]
```

Not sure if the .value part is needed or if it will automatically evaluate to str.

2022-02-11 16:44 UTC, abernathyc approved these changes

2022-02-11 17:54 UTC, merged